https://medium.com/datadriveninvestor/a-simple-guide-to-creating-predictive-models-in-python-part-1-8e3ddc3d7008

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 976.6+ KB

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
class OptionTrade:
  def __init__(self, stock_price, strike_price, risk_free_rate,    volatility, time_to_maturity):
        self.stock_price=stock_price
        self.strike_price=strike_price
        self.risk_free_rate=risk_free_rate
        self.volatility=volatility
        self.time_to_maturity = time_to_maturity

In [4]:
class GBMModel:
    def __init__(self, Configuration):
        self.Configuration = Configuration
        
    #simulate risk factors using GBM stochastic differential equation
    def SimulateRiskFactor(self, trade):
        prices = []
        # for this example, we only are concerned with one time step as it's an European option
        timestep = 1
        for scenarioNumber in range(self.Configuration.NumberOfScenarios):
            normal_random_number = np.random.normal(0, 1)           
            drift = trade.risk_free_rate-0.5*(trade.volatility**2)*timestep
            uncertainty =trade.volatility*np.sqrt(timestep)*normal_random_number
            price = trade.stock_price * np.exp(drift+uncertainty)
            prices.append(price)    
        return prices

In [5]:
class OptionTradePayoffPricer:
    def CalculatePrice(self, trade, prices_per_scenario):
        pay_offs = 0
        total_scenarios = len(prices_per_scenario)
        for i in range(total_scenarios):
            price = prices_per_scenario[i]
            pay_off = price - trade.strike_price
            if(pay_off>0): 
                pay_offs=pay_offs+pay_off
        
        discounted_price = (np.exp(-1.0*trade.risk_free_rate * trade.time_to_maturity)*pay_offs)
        result = discounted_price/total_scenarios
        return result

In [12]:
def plot_scenario_paths(prices_per_scenario):
     x=[]
     y=[]
     for i in prices_per_scenario:
            y.append(i)
            y.append(trade.stock_price)
            x.append(1)            
            x.append(0)            
            plt.plot(x, y)            
       
      #plt.ylabel('StockValue')
      #plt.xlabel('Timestep')
      #plt.show()

In [13]:
class MonteCarloEngineSimulator:
    
    #instationate with configuration and the model
    def __init__(self, configuration, model):
        self.configuration = configuration
        self.model = model
        
    #simulate trade and calculate price    
    def Simulate(self, trade, tradePricer):
        prices_per_scenario = self.model.SimulateRiskFactor(trade)
        #plot scenarios
        plot_scenario_paths(prices_per_scenario)
        price = tradePricer.CalculatePrice(trade, prices_per_scenario)
        
        return pricec

In [14]:
def Main():
    #prepare the data
    configuration = Configuration(10, 1) # config
    trade = OptionTrade(200, 200, 0.15, 0.1,1) # trade
    model = GBMModel(configuration)
    tradePricer = OptionTradePayoffPricer()
    simulator = MonteCarloEngineSimulator(configuration, model)
    
    #simulate price
    price = simulator.Simulate(trade, tradePricer)
    print(price)